version: '3'
services:
  intel-test:
    build:
      context: ""
      dockerfile: ./Dockerfile.intel-test
    image: intel-test:latest
    entrypoint:
      - /bin/entrypoint.sh
    env_file:
      - intel-test.env
    ports:
      - "5678"
    environment:
      - VIRTUAL_HOST=intel
      - VIRTUAL_PORT=5678
      - SERVICE_PORT=5678
      - PG_HOST=db-test
      - PG_PORT=5432
      - PG_DBNAME=postgres
      - PG_USER=postgres
      - PG_PASSWORD=postgres
    depends_on:
      db-test:
        condition: service_healthy
  db-test:
    restart: always
    image: postgres:alpine
    ports:
      - "3456:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./var/pgdata/intel-test:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
